"""
File: main.py

Author: Damien ESNAULT (PhD student)
Institution: ENSTA/Lab-STICC
Date: 2025

Summary:
    Generate and export deterministic and stochastic 2D Dubins-car trajectories
    for the OCEANS 2025 mission scenario.

Description:
    This script generates a reference trajectory and a set of noisy trajectory
    realizations for a Dubins-car system. These exported trajectories are intended
    to be used later in the C++ part of the repository with the IntervalMonteCarlo
    class in order to estimate probability bounds of detecting multiple objects
    along a mission.

    The reference trajectory corresponds to the solution of the nominal Dubins-car
    dynamics without noise. The noisy trajectories are generated by perturbing the
    heading command with Gaussian noise at each integration step. This produces a
    progressive drift from the nominal path, similar to the behavior of a robot
    navigating by dead reckoning.

    The exported trajectories are saved in two formats:
        - plain text arrays for quick inspection and plotting,
        - serialized CODAC TubeVectors for interval-based processing in C++.

Export structure:
    <output_dir>/
    ├── Perfect/
    │   ├── simulation_numpy_array.txt
    │   └── simulation.tubevector
    └── Noisy/
        ├── simulation1_numpy_array.txt
        ├── simulation1.tubevector
        ├── simulation2_numpy_array.txt
        ├── simulation2.tubevector
        └── ...

Typical use:
    python main.py 
    python main.py --debug 
    python main.py --num-samples 100 
    python main.py --num-samples 1000 --debug

"""

# =============================================================================
# IMPORT LIBRARIES
# =============================================================================

import argparse
from pathlib import Path

import codac
import numpy as np
import matplotlib.pyplot as plt

from dubins_car import DubinsCar


# =============================================================================
# CUSTOM DUBINS CAR CLASS
# =============================================================================

class MyCustomDubinsCar(DubinsCar):
    """
    Custom Dubins-car model used to generate the OCEANS 2025 trajectory dataset.

    This class defines:
        - a nominal speed regulator,
        - a time-dependent heading command,
        - an additive Gaussian noise model on the heading command.

    The resulting noisy trajectories progressively drift away from the nominal
    reference trajectory, which mimics the behavior of a robot affected by
    dead-reckoning navigation uncertainty.
    """

    def __init__(self, initial_state_vector=(0.0, 0.0, 0.0, 0.0), heading_noise_mean=0.0, heading_noise_std=0.0, random_generator=None):
        """
        Initialize the custom Dubins-car model.

        Args:
            initial_state_vector (tuple, list, or np.ndarray, optional):
                Initial state [x0, y0, heading0, speed0].

            heading_noise_mean (float, optional):
                Mean of the Gaussian noise added to the heading command.

            heading_noise_std (float, optional):
                Standard deviation of the Gaussian noise added to the heading command.

            random_generator (np.random.Generator, optional):
                NumPy random number generator used to draw heading noise.
        """
        super().__init__(initial_state_vector)

        self.heading_noise_mean = float(heading_noise_mean)
        self.heading_noise_std = float(heading_noise_std)

        if random_generator is None:
            self.random_generator = np.random.default_rng()
        else:
            self.random_generator = random_generator

    def compute_command_vector(self, state_vector, simulation_time):
        """
        Compute the command vector applied to the Dubins car.

        The speed is regulated toward a constant desired value.
        The heading command is a smooth time-dependent function designed to
        generate a long survey-like trajectory. A Gaussian perturbation is added
        to the heading command in order to create stochastic trajectory realizations.

        Args:
            state_vector (np.ndarray):
                Current state [x, y, heading, speed].

            simulation_time (float):
                Current simulation time.

        Returns:
            np.ndarray:
                Command vector [heading_rate, acceleration].
        """
        # Get current state variables
        px, py, heading, speed = np.array(state_vector, dtype=float).flatten()

        # Speed regulator
        desired_speed = 2.0
        speed_gain = 1.0
        acceleration = speed_gain * (desired_speed - speed)

        # Nominal heading command
        heading_rate_nominal = 0.08 * np.sin(0.18 * simulation_time) + 0.03 * np.sin(0.55 * simulation_time)

        # Stochastic perturbation
        heading_noise = self.random_generator.normal(self.heading_noise_mean, self.heading_noise_std)
        heading_rate_noisy = heading_rate_nominal + heading_noise

        # Return command vector
        return np.array([heading_rate_noisy, acceleration], dtype=float)

    def mission_is_completed(self, state_vector, simulation_time):
        """
        Mission completion criterion.

        In this trajectory-generation script, the simulation always runs until the
        maximal simulation duration is reached.

        Args:
            state_vector (np.ndarray):
                Current state [x, y, heading, speed].

            simulation_time (float):
                Current simulation time.

        Returns:
            bool:
                Always False.
        """
        return False


# =============================================================================
# EXPORT FUNCTION
# =============================================================================

def export_simulation(dubins_car: DubinsCar, output_directory: Path, time_step: float, simulation_number: int = None):
    """
    Export a Dubins-car simulation to disk.

    Two files are generated:
        1) a text file containing the sampled trajectory:
           [t, x, y, theta, v]

        2) a serialized CODAC TubeVector (.tubevector) for direct use in the
           downstream C++ interval-based pipeline.

    Args:
        dubins_car (DubinsCar):
            Simulated Dubins-car instance containing recorded trajectories.

        output_directory (Path):
            Directory where the exported files will be written.

        time_step (float):
            Integration time step used to build the TubeVector.

        simulation_number (int, optional):
            Identifier for noisy simulations. If None, generic filenames are used
            (typically for the perfect/reference trajectory).

    Raises:
        ValueError:
            If the recorded trajectory is empty or has inconsistent dimensions.
    """
    
    # Extract trajectories
    time_trajectory = np.array(dubins_car.time_trajectory, dtype=float)
    state_trajectory = np.array(dubins_car.state_vector_trajectory, dtype=float)

    # Verify format
    if time_trajectory.size == 0 or state_trajectory.size == 0:
        raise ValueError("export_simulation(): empty trajectory, nothing to export.")

    if state_trajectory.ndim != 2 or state_trajectory.shape[1] != 4:
        raise ValueError("export_simulation(): state_trajectory must have shape (N, 4).")

    if time_trajectory.shape[0] != state_trajectory.shape[0]:
        raise ValueError("export_simulation(): time and state trajectories must have the same length.")

    # Build export array
    # Exported text format: [t, x, y, theta, v]
    simulation_trajectory = np.hstack((time_trajectory[:, np.newaxis], state_trajectory))

    # Define output filenames
    if simulation_number is None:
        numpy_array_filename = output_directory / "simulation_numpy_array.txt"
        tubevector_filename = output_directory / "simulation.tubevector"
    else:
        numpy_array_filename = output_directory / f"simulation{simulation_number}_numpy_array.txt"
        tubevector_filename = output_directory / f"simulation{simulation_number}.tubevector"

    # Export text file
    np.savetxt(numpy_array_filename, simulation_trajectory, header="t x y theta v")

    # Build codac tubevector
    codac_trajectory_vector = codac.TrajectoryVector(4)
    codac_trajectory_vector[0] = codac.Trajectory(time_trajectory, state_trajectory[:, 0])
    codac_trajectory_vector[1] = codac.Trajectory(time_trajectory, state_trajectory[:, 1])
    codac_trajectory_vector[2] = codac.Trajectory(time_trajectory, state_trajectory[:, 2])
    codac_trajectory_vector[3] = codac.Trajectory(time_trajectory, state_trajectory[:, 3])
    codac_tube_vector = codac.TubeVector(codac_trajectory_vector, time_step)

    # Export codac tubevector
    codac_tube_vector.serialize(str(tubevector_filename))


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":

    # -------------------------------------------------------------------------
    # PARSE USER ARGUMENTS
    # -------------------------------------------------------------------------

    script_dir = Path(__file__).resolve().parent

    parser = argparse.ArgumentParser(description="Generate and export deterministic and stochastic Dubins-car trajectories for the OCEANS 2025 scenario.")

    parser.add_argument("--num-samples", type=int, default=500, help="Number of noisy simulations to generate and export (default: 500).")
    parser.add_argument("--output-dir", type=str, default="oceans2025", help="Name of the output directory created inside the output path (default: oceans2025).")
    parser.add_argument("--output-path", type=str, default=str(script_dir), help="Path where the output directory must be created (default: directory of this script).")
    parser.add_argument("--seed", type=int, default=8734942, help="Seed of the random generator used for reproducible trajectory generation (default: 8734942).")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode: display detailed execution information and a trajectory plot.")

    args = parser.parse_args()

    # -------------------------------------------------------------------------
    # CHECK USER ARGUMENTS
    # -------------------------------------------------------------------------

    if args.num_samples <= 0:
        raise ValueError("main.py: --num-samples must be strictly greater than 0.")

    if args.seed <= 0:
        raise ValueError("main.py: --seed must be strictly greater than 0.")

    if args.debug:
        print("\n[DEBUG] Script parameters:")
        print(f"\t- Number of samples: {args.num_samples}")
        print(f"\t- Output directory: {args.output_dir}")
        print(f"\t- Output path: {args.output_path}")
        print(f"\t- Random seed: {args.seed}")
        print(f"\t- Debug mode: {args.debug}")

    # -------------------------------------------------------------------------
    # CHECK OUTPUT PATH AND CREATE DIRECTORIES
    # -------------------------------------------------------------------------

    output_path = Path(args.output_path)

    if not output_path.exists():
        raise FileNotFoundError(f"main.py: output path does not exist: {output_path}")

    if not output_path.is_dir():
        raise NotADirectoryError(f"main.py: output path is not a directory: {output_path}")

    output_directory_path = output_path / args.output_dir

    if output_directory_path.exists():
        raise RuntimeError(f"main.py: output directory already exists: {output_directory_path}")

    output_directory_path.mkdir()

    perfect_directory_path = output_directory_path / "Perfect"
    noisy_directory_path = output_directory_path / "Noisy"

    perfect_directory_path.mkdir()
    noisy_directory_path.mkdir()

    # -------------------------------------------------------------------------
    # GLOBAL PARAMETERS
    # -------------------------------------------------------------------------

    random_generator = np.random.default_rng(args.seed)

    # Gaussian noise applied to the heading command
    heading_noise_mean = 0.0
    heading_noise_std = np.pi/50.0

    # Simulation parameters
    duration = 30.0
    time_step = 0.05

    # Initial state [x0, y0, heading0, speed0]
    initial_state = (0.0, 0.0, 0.0, 0.0)

    if args.debug:
        print("\n[DEBUG] Simulation parameters:")
        print(f"\t- Mission duration: {duration} s")
        print(f"\t- Integration time step: {time_step} s")
        print(f"\t- Initial state vector: {initial_state}")
        print(f"\t- Heading noise mean: {heading_noise_mean}")
        print(f"\t- Heading noise standard deviation: {heading_noise_std}")

    # -------------------------------------------------------------------------
    # GENERATE PERFECT REFERENCE TRAJECTORY
    # -------------------------------------------------------------------------

    perfect_dubins_car = MyCustomDubinsCar(
        initial_state_vector=initial_state,
        heading_noise_mean=0.0,
        heading_noise_std=0.0,
        random_generator=np.random.default_rng(0)
    )

    perfect_dubins_car.run_simulation(duration, time_step)
    print("\n[SIMULATION] Reference trajectory generated successfully.")

    export_simulation(perfect_dubins_car, perfect_directory_path, time_step)
    print("[EXPORT] Reference trajectory exported successfully.\n")

    # -------------------------------------------------------------------------
    # OPTIONAL DEBUG FIGURE
    # -------------------------------------------------------------------------

    if args.debug:   
        plt.figure(figsize=(8, 6))

    # -------------------------------------------------------------------------
    # GENERATE AND EXPORT NOISY TRAJECTORIES
    # -------------------------------------------------------------------------

    for i in range(args.num_samples):
        print(f"[SIMULATION] Simulation {i + 1}/{args.num_samples}")

        # Create one independent RNG per trajectory for reproducibility
        simulation_seed = int(random_generator.integers(0, 2**32 - 1))
        simulation_rng = np.random.default_rng(simulation_seed)

        dubins_car = MyCustomDubinsCar(
            initial_state_vector=initial_state,
            heading_noise_mean=heading_noise_mean,
            heading_noise_std=heading_noise_std,
            random_generator=simulation_rng
        )

        dubins_car.run_simulation(duration, time_step, debug_print=args.debug)
        export_simulation(dubins_car, noisy_directory_path, time_step, simulation_number=i + 1)

        print("[EXPORT] Simulation exported successfully.\n")

        if args.debug:
            trajectory = np.array(dubins_car.state_vector_trajectory)
            plt.plot(trajectory[:, 0], trajectory[:, 1], alpha=0.7, zorder=0)

    # -------------------------------------------------------------------------
    # DEBUG DISPLAY
    # -------------------------------------------------------------------------

    if args.debug:
        perfect_trajectory = np.array(perfect_dubins_car.state_vector_trajectory)

        plt.plot(
            perfect_trajectory[:, 0],
            perfect_trajectory[:, 1],
            color="black",
            linewidth=2,
            zorder=10,
            label="Reference trajectory"
        )

        plt.xlabel("x axis (m)")
        plt.ylabel("y axis (m)")
        plt.title("Generated Dubins-car trajectories for the OCEANS 2025 scenario")
        plt.grid(True)
        plt.axis("equal")
        plt.legend()
        plt.tight_layout()
        plt.show()

    print(f"[DONE] Generated and exported {args.num_samples} noisy trajectory sample(s) in: {output_directory_path}")